## Pandas Complete tutorial for data science in 2026

In [1]:
# importing libraries
import numpy as np
import pandas as pd

## 2.Loading Different Data Formats Into a Pandas Data Frame

In [2]:
# Import Dataset
df=pd.read_csv("C:\\pandas\\dataset\\online_store_customer_data.csv")

In [3]:
df

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,NaN,1199.79
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [4]:
df.head()

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,NaN,1199.79
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN

In [5]:
df.tail(7)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
2505,4/30/2021,153693,Male,54.0,Married,Alabama,Basic,Employees,Card,0.0,266.61
2506,4/30/2021,153694,Male,34.0,Single,Florida,Missing,Employees,Other,1.0,286.82
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [6]:
df.shape

(2512, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_date  2512 non-null   object
 1   Transaction_ID    2512 non-null   int64
 2   Gender            2484 non-null   object
 3   Age               2470 non-null   float64
 4   Marital_status    2512 non-null   object
 5   State_names       2512 non-null   object
 6   Segment           2512 non-null   object
 7   Employees_status  2486 non-null   object
 8   Payment_method    2512 non-null   object
 9   Referal           2356 non-null   float64
 10  Amount_spent      2270 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 216.0+ KB

In [8]:
# loading csv file with first 2 rows without header
df = pd.read_csv('C:\\pandas\\dataset\\online_store_customer_data.csv',skiprows=2)

In [9]:
# Loading csv file with skip first 2 rows without header
df_csv = pd.read_csv('C:\\pandas\\dataset\\online_store_customer_data.csv',skiprows=3)
df_csv.head()

,1/1/2019,151202,Male,63,Married,New Mexico,Basic,workers,PayPal,1,1572.6
0,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,NaN,1199.79
1,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
2,1/3/2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
3,1/3/2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
4,1/3/2019,151207,Male,37.0,Married,Connecticut,Basic,workers,PayPal,1.0,1149.55

## Read CSV file from URL

In [10]:
# Read CSV file from URL
url1="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df_url = pd.read_csv(url1)
df_url

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [11]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\dell\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\dell\anaconda3\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\dell\anaconda3\lib\site-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
# import the dataset 
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets 
  
# metadata 
print(car_evaluation.metadata) 
  
# variable information 
print(car_evaluation.variables)

{'uci_id': 19, 'name': 'Car Evaluation', 'repository_url': 'https://archive.ics.uci.edu/dataset/19/car+evaluation', 'data_url': 'https://archive.ics.uci.edu/static/public/19/data.csv', 'abstract': 'Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1728, 'num_features': 6, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1988, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5JP48', 'creators': ['Marko Bohanec'], 'intro_paper': {'ID': 249, 'type': 'NATIVE', 'title': 'Knowledge acquisition and explanation for multi-attribute decision making', 'authors': 'M. Bohanec, V. Rajkovič', 'venue': '8th Intl Workshop on Expert Systems and their Applications, Avignon, France', 'year': 1988, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/KNOWLEDGE-ACQUISITION-AND-EXPLANATION-FOR-DECISION-Bohanec-Rajkovi%C4%8D/8bab443ae322ff47c3e609272bd93fd4650555bc', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Car Evaluation Database was derived from a simple hierarchical decision model originally developed for the demonstration of DEX, M. Bohanec, V. Rajkovic: Expert system for decision making. Sistemica 1(1), pp. 145-157, 1990.). The model evaluates cars according to the following concept structure:\r\n\r\nCAR                      car acceptability\r\n. PRICE                  overall price\r\n. . buying               buying price\r\n. . maint                price of the maintenance\r\n. TECH                   technical characteristics\r\n. . COMFORT              comfort\r\n. . . doors              number of doors\r\n. . . persons            capacity in terms of persons to carry\r\n. . . lug_boot           the size of luggage boot\r\n. . safety               estimated safety of the car\r\n\r\nInput attributes are printed in lowercase. Besides the target concept (CAR), the model includes three intermediate concepts: PRICE, TECH, COMFORT. Every concept is in the original model related to its lower level descendants by a set of examples (for these examples sets see http://www-ai.ijs.si/BlazZupan/car.html).\r\n\r\nThe Car Evaluation Database contains examples with the structural information removed, i.e., directly relates CAR to the six input attributes: buying, maint, doors, persons, lug_boot, safety.\r\n\r\nBecause of known underlying concept structure, this database may be particularly useful for testing constructive induction and structure discovery methods.\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'buying:   vhigh, high, med, low.\nmaint:    vhigh, high, med, low.\ndoors:    2, 3, 4, 5more.\npersons:  2, 4, more.\nlug_boot: small, med, big.\nsafety:   low, med, high.', 'citation': None}}
       name     role         type demographic  \
0    buying  Feature  Categorical        None
1     maint  Feature  Categorical        None
2     doors  Feature  Categorical        None
3   persons  Feature  Categorical        None
4  lug_boot  Feature  Categorical        None
5    safety  Feature  Categorical        None
6     class   Target  Categorical        None

                                         description units missing_values
0                                       buying price  None             no
1                           price of the maintenance  None             no
2                                    number of doors  None             no
3              capacity in terms of persons to carry  None             no
4                           the size of luggage boot  None             no
5                        estimated safety of the car  None             no
6  evaulation level (unacceptable, acceptable, go...  None             no

# Write CSV file

# Read text file

In [13]:
# read plain text file 
df_txt = pd.read_csv("C:\\pandas\\dataset\\demo_text.txt")
df_txt

   Hello
0       1
1       2
2       3

# read Excel file

In [14]:
# read excel file
df_excel = pd.read_excel('C:\\pandas\\dataset\\excel_file.xlsx',sheet_name='Data')
df_excel

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent,Transaction_ID.1
0,3/10/2019,151378,Female,25,Single,Wyoming,Platinum,Unemployment,Card,1,2740.57,151378
1,7/2/2019,151751,Female,42,Single,Delaware,Basic,Unemployment,Card,0,977.80,151751
2,6/14/2019,151689,Male,38,Married,Montana,Basic,workers,PayPal,1,2978.21,151689
3,8/5/2019,151849,Male,24,Married,Rhode Island,Basic,workers,Card,1,1157.79,151849

In [15]:
# save dataframe to the excel file
df_url.to_csv('demo.xlsx')

# 3.1 data exploring

# Retrieving sample rows from data frame

In [16]:
# display random 7 sample rows
df.sample(7)

,1/1/2019,151201,Male,49,Single,Illinois,Basic,self-employed,Card,0,544.04
1533,5/30/2020,152723,Female,54.0,Single,Illinois,Basic,workers,Card,1.0,1762.21
1339,3/17/2020,152529,Male,43.0,Single,New Mexico,Platinum,self-employed,PayPal,1.0,828.36
1302,3/2/2020,152492,Male,26.0,Married,Maryland,Silver,Employees,PayPal,1.0,8.67
2205,1/20/2021,153395,Female,59.0,Married,Minnesota,Missing,Employees,PayPal,1.0,2767.44
2044,11/22/2020,153234,Female,26.0,Married,New Hampshire,Basic,workers,Other,0.0,2417.10
1210,1/30/2020,152400,Female,76.0,Married,Alaska,Basic,Employees,PayPal,0.0,1207.82
253,3/31/2019,151443,Female,76.0,Single,Vermont,Platinum,Employees,Other,1.0,1672.01

# Retrieving information about dataframe

In [17]:
# display datatypes
df.dtypes

1/1/2019          object
151201             int64
Male              object
49               float64
Single            object
Illinois          object
Basic             object
self-employed     object
Card              object
0                float64
544.04           float64
dtype: object

In [18]:
df.dtypes.value_counts()

object     7
float64    3
int64      1
Name: count, dtype: int64

# Display numbers of rows and columns.

In [19]:
df.columns

Index(['1/1/2019', '151201', 'Male', '49', 'Single', 'Illinois', 'Basic',
       'self-employed', 'Card', '0', '544.04'],
      dtype='object')

In [20]:
#display Age columns first 6 rows data
df_excel['Age'].head(6)

0    25
1    42
2    38
3    24
Name: Age, dtype: int64

# 3.2 Data clianing

## Delete Columns name

In [21]:
# Dropunwanted columns
df_excel.drop(['Transaction_ID'],axis=1,inplace=True)

# Change the columns name

In [22]:
df_excel

,Transaction_date,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent,Transaction_ID.1
0,3/10/2019,Female,25,Single,Wyoming,Platinum,Unemployment,Card,1,2740.57,151378
1,7/2/2019,Female,42,Single,Delaware,Basic,Unemployment,Card,0,977.80,151751
2,6/14/2019,Male,38,Married,Montana,Basic,workers,PayPal,1,2978.21,151689
3,8/5/2019,Male,24,Married,Rhode Island,Basic,workers,Card,1,1157.79,151849

In [23]:
df_col = pd.read_csv('C:\\pandas\\dataset\\online_store_customer_data.csv')

# Adding a new column to a DataFrame

In [24]:
# add a new ajusted column whith value will be amount_spent + 10
df_col['Test'] = df_col['Amount_spent'] * 10

In [25]:
df_col.head(3)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent,Test
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36,20513.6
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04,5440.4
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60,15726.0

In [29]:
# changing female to woman and woman to male
df_col.loc[df_col['Gender'] == 'Female', 'Gender'] = 'Woman'
df_col.loc[df_col['Gender'] == 'Male', 'Gender'] = 'Man'

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2510 entries, 0 to 2509
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   1/1/2019       2510 non-null   object
 1   151201         2510 non-null   int64
 2   Male           2482 non-null   object
 3   49             2468 non-null   float64
 4   Single         2510 non-null   object
 5   Illinois       2510 non-null   object
 6   Basic          2510 non-null   object
 7   self-employed  2484 non-null   object
 8   Card           2510 non-null   object
 9   0              2354 non-null   float64
 10  544.04         2268 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 215.8+ KB

In [30]:
df_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_date  2512 non-null   object
 1   Transaction_ID    2512 non-null   int64
 2   Gender            2484 non-null   object
 3   Age               2470 non-null   float64
 4   Marital_status    2512 non-null   object
 5   State_names       2512 non-null   object
 6   Segment           2512 non-null   object
 7   Employees_status  2486 non-null   object
 8   Payment_method    2512 non-null   object
 9   Referal           2356 non-null   float64
 10  Amount_spent      2270 non-null   float64
 11  Test              2270 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 235.6+ KB

In [31]:
# change object type to datefime64 format
df_col['Transaction_date'] = df_col['Transaction_date'].astype('datetime64[ns]')

# change float64 to float32 of Referal columns
df_col['Referal'] = df_col['Referal'].astype('float32')

In [32]:
print(df_col.columns.tolist())

['Transaction_date', 'Transaction_ID', 'Gender', 'Age', 'Marital_status', 'State_names', 'Segment', 'Employees_status', 'Payment_method', 'Referal', 'Amount_spent', 'Test']

In [33]:
df_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_date  2512 non-null   datetime64[ns]
 1   Transaction_ID    2512 non-null   int64
 2   Gender            2484 non-null   object
 3   Age               2470 non-null   float64
 4   Marital_status    2512 non-null   object
 5   State_names       2512 non-null   object
 6   Segment           2512 non-null   object
 7   Employees_status  2486 non-null   object
 8   Payment_method    2512 non-null   object
 9   Referal           2356 non-null   float32
 10  Amount_spent      2270 non-null   float64
 11  Test              2270 non-null   float64
dtypes: datetime64[ns](1), float32(1), float64(3), int64(1), object(6)
memory usage: 225.8+ KB

In [34]:
print(df_col.columns)

Index(['Transaction_date', 'Transaction_ID', 'Gender', 'Age', 'Marital_status',
       'State_names', 'Segment', 'Employees_status', 'Payment_method',
       'Referal', 'Amount_spent', 'Test'],
      dtype='object')

In [35]:
print(df_col['Gender'])

0       Woman
1         Man
2         Man
3         NaN
4         Man
        ...
2507    Woman
2508    Woman
2509      Man
2510      NaN
2511      Man
Name: Gender, Length: 2512, dtype: object

# 3.3 Remove dublicate

In [38]:
# display dublicated 
df_col.duplicated().sum()

np.int64(12)

In [39]:
# display dublicated 
df_col.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [40]:
# duplicated rows display, keep arguments will--- 'first','last' 
duplicate_value = df.duplicated(keep='first')
duplicate_value
df.loc[duplicate_value,:]

,1/1/2019,151201,Male,49,Single,Illinois,Basic,self-employed,Card,0,544.04
62,1/25/2019,151259,Male,73.0,Married,West Virginia,Basic,Employees,PayPal,0.0,1397.09
63,1/26/2019,151260,Male,55.0,Married,Kansas,Basic,Employees,Other,1.0,1277.64
64,1/26/2019,151261,Female,72.0,Married,Iowa,Silver,Unemployment,PayPal,NaN,515.77
65,1/26/2019,151262,Male,15.0,Married,South Carolina,Basic,self-employed,Other,1.0,790.10
66,1/27/2019,151263,Female,63.0,Single,Texas,Gold,Employees,Card,1.0,1218.56
107,2/6/2019,151297,Male,60.0,Married,Utah,Silver,Unemployment,Other,1.0,433.20
108,2/7/2019,151298,Female,45.0,Married,Missouri,Platinum,workers,Other,1.0,929.89
109,2/8/2019,151299,Male,33.0,Single,Arizona,Silver,workers,PayPal,0.0,2560.26
110,2/8/2019,151300,Male,24.0,Married,South Carolina,Basic,Unemployment,Other,0.0,NaN
111,2/8/2019,151301,Female,53.0,Single,Colorado,Basic,self-employed,Other,1.0,1888.69
112,2/8/2019,151302,Female,70.0,Married,New Hampshire,Missing,Employees,Card,1.0,685.49
113,2/8/2019,151303,Male,16.0,Married,Nebraska,Basic,workers,PayPal,1.0,1264.73

In [43]:
# dropping all duplicate values
df.drop_duplicates(keep = 'first' , inplace = True)
df.drop_duplicates()

,1/1/2019,151201,Male,49,Single,Illinois,Basic,self-employed,Card,0,544.04
0,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
1,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,NaN,1199.79
2,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
3,1/3/2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
4,1/3/2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
...,...,...,...,...,...,...,...,...,...,...,...
2505,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2506,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2507,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2508,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2509,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

# 3.4 Handling missing values

Handling missing values in the common task in the data pre-processing part.

# Display missing values information

In [45]:
df.isna().sum().sort_values(ascending=False)

544.04           241
0                155
49                42
Male              28
self-employed     26
1/1/2019           0
151201             0
Single             0
Illinois           0
Basic              0
Card               0
dtype: int64

In [46]:
df_new.drop(columns=['Amount_spent'], inplace=True)

NameError: name 'df_new' is not defined